# Generated by Django 2.2.7 on 2020-01-18 16:08

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0026_auto_20190918_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='baginfometadata',
            name='origin',
            field=models.CharField(default='aurora', max_length=10),
        ),
        migrations.AlterField(
            model_name='archives',
            name='accession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accession_transfers', to='bag_transfer.Accession'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='user_uploaded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
